<?php

namespace AppBundle\Repository;

/**
 * ComentariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentariosRepository extends \Doctrine\ORM\EntityRepository
{
}
