<?php

namespace AppBundle\Repository;

/**
 * SeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
