<?php

namespace AppBundle\Repository;

/**
 * TemasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemasRepository extends \Doctrine\ORM\EntityRepository
{
}
