user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.tema:
    resource: "@AppBundle/Controller/TemasController.php"
    type: annotation

app.comentario:
    resource: "@AppBundle/Controller/ComentariosController.php"
    type: annotation

app.tema2:
    resource: "@AppBundle/Controller/Admin/TemasController.php"
    type: annotation

app.comentario2:
    resource: "@AppBundle/Controller/Admin/ComentariosController.php"
    type: annotation

app.index2:
    resource: "@AppBundle/Controller/Admin/IndexController.php"
    type: annotation